### ISSUE TITLE
test error！！

### ISSUE THREAD

**Issue by tsing-cv** [ZJULearning/pixel_link#12]
```
(tf3_w) ??@thinkstation:~/w/pixel_link$ ./scripts/test.sh 0 ~/w/pixel_link/pixel_link_vgg_2s/conv2_2/model.ckpt-73018.data-00000-of-00001 ~/w/pixel_link/datasets/data
++ set -e
++ export CUDA_VISIBLE_DEVICES=0
++ CUDA_VISIBLE_DEVICES=0
++ python test_pixel_link.py --checkpoint_path=/home/??/w/pixel_link/pixel_link_vgg_2s/conv2_2/model.ckpt-73018.data-00000-of-00001 --dataset_dir=/home/??/w/pixel_link/datasets/data --gpu_memory_fraction=-1
INFO:tensorflow:loading config.py from /home/??/w/pixel_link/pixel_link_vgg_2s/conv2_2/config.py
test_pixel_link_on_icdar2015
Traceback (most recent call last):
  File "test_pixel_link.py", line 176, in <module>
    tf.app.run()
  File "/home/??/anaconda2/envs/tf3_w/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "test_pixel_link.py", line 171, in main
    config_initialization()
  File "test_pixel_link.py", line 79, in config_initialization
    util.proc.set_proc_name('test_pixel_link_on'+ '_' + FLAGS.dataset_name)
  File "/home/??/w/pixel_link/pylib/src/util/proc.py", line 21, in set_proc_name
    setproctitle.setproctitle(name)
UnboundLocalError: local variable 'setproctitle' referenced before assignment
```
你好，在测试的过程中，我出现了下面的报错，我不知道怎么解决这个问题，可以帮我解答一下吗？

**Comment by tsing-cv** [comment]
Solved

**Comment by zxDeepDiver** [comment]
Could you please tell me how to solve it?

**Comment by zxDeepDiver** [comment]
solved by 
`pip install setproctitle`

**Comment by Dugujiujian12321** [comment]
How to solve this problem? thank you

**Comment by ansul26** [comment]
Solved

**Comment by gachiemchiep** [comment]
@chunklarry 

Worked man. Thank you
