### ISSUE TITLE
TypeError: Can not convert a list into a Tensor or Operation.

### ISSUE THREAD

**Issue by Lanme** [ZJULearning/pixel_link#158]
When I run "./scripts/train.sh 0,1 8" ：
> Traceback (most recent call last):
  File "train_pixel_link.py", line 293, in <module>
    tf.app.run()
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_pixel_link.py", line 288, in main
    train_op = create_clones(batch_queue)
  File "train_pixel_link.py", line 252, in create_clones
    train_op = control_flow_ops.with_dependencies(train_ops, pixel_link_loss, name='train_op')
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3368, in with_dependencies
    with ops.control_dependencies(dependencies):
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5004, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4543, in control_dependencies
    c = self.as_graph_element(c)
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/ai/installs/anaconda3/envs/py27_tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3579, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a list into a Tensor or Operation.

opencv_version:2.4.13.4
python:2.7.15
tensorflow:1.12
cuda:9.0

After I change tensorflow1.12 to tensorflow1.1,the problem still remains.

**Comment by Lanme** [comment]
> if bn_update_op is not None:

change this line into :

>if bn_update_op!=[]:
        train_ops.append(bn_update_op)
